quarkus.quinoa.package-manager-install.node-version=20.10.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=quinoa

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=marin
quarkus.datasource.password=Petimodz0000

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/facile

# quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.database.generation=update

# quarkus.rest-client.navitia-api.url = https://dictionary.lewagon.com
quarkus.rest-client.navitia-api.url=https://api.navitia.io/v1/coverage
# quarkus.rest-client.navitia-api.url = https://287e5a3b-64ec-412c-b910-7ae2efe4cb2b@api.navitia.io/v1/coverage

# API sncf : https://api.navitia.io/v1/coverage/sncf/
# clé api sncf : "287e5a3b-64ec-412c-b910-7ae2efe4cb2b"

# Active CORS
quarkus.http.cors=true

# # Autorise ton frontend Angular
quarkus.http.cors.origins=http://localhost:4200
# quarkus.http.cors.origins=http://127.0.0.1:4200

# # (Optionnel) Autorise les headers spécifiques
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# # (Optionnel) Autorise les méthodes nécessaires
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS


# Active les logs détaillés pour les appels REST clients
# quarkus.log.level=DEBUG
# quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
# quarkus.log.category."io.quarkus.rest.client.reactive".level=DEBUG

# # (optionnel) pour voir aussi les requêtes entrantes côté serveur
# quarkus.log.category."io.quarkus.resteasy.reactive.server".level=DEBUG
